/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as accountSwitch from "../accountSwitch.js";
import type * as admin_mergeUser from "../admin_mergeUser.js";
import type * as agentDefinitions from "../agentDefinitions.js";
import type * as agentPromptRepair from "../agentPromptRepair.js";
import type * as agentSchema from "../agentSchema.js";
import type * as agentTasks from "../agentTasks.js";
import type * as analytics from "../analytics.js";
import type * as anchors from "../anchors.js";
import type * as apiTokens from "../apiTokens.js";
import type * as apns from "../apns.js";
import type * as apnsProviderToken from "../apnsProviderToken.js";
import type * as apnsVoip from "../apnsVoip.js";
import type * as appConnections from "../appConnections.js";
import type * as artifactMarkdown from "../artifactMarkdown.js";
import type * as artifactPages from "../artifactPages.js";
import type * as artifacts from "../artifacts.js";
import type * as artifactsHttp from "../artifactsHttp.js";
import type * as assistant_entry from "../assistant/entry.js";
import type * as assistant_history from "../assistant/history.js";
import type * as assistant_input from "../assistant/input.js";
import type * as assistant_routines from "../assistant/routines.js";
import type * as assistant_tools_codecast from "../assistant/tools/codecast.js";
import type * as assistant_tools_index from "../assistant/tools/index.js";
import type * as assistant_tools_web from "../assistant/tools/web.js";
import type * as assistant_tools_workspace from "../assistant/tools/workspace.js";
import type * as assistant_turns from "../assistant/turns.js";
import type * as assistantSchema from "../assistantSchema.js";
import type * as auth from "../auth.js";
import type * as billing from "../billing.js";
import type * as blame from "../blame.js";
import type * as blameCore from "../blameCore.js";
import type * as bookmarkViewWrites from "../bookmarkViewWrites.js";
import type * as bookmarks from "../bookmarks.js";
import type * as buckets from "../buckets.js";
import type * as callChat from "../callChat.js";
import type * as callFace from "../callFace.js";
import type * as callGuests from "../callGuests.js";
import type * as callRecordings from "../callRecordings.js";
import type * as callRooms from "../callRooms.js";
import type * as calls from "../calls.js";
import type * as capabilities from "../capabilities.js";
import type * as capabilitiesSchema from "../capabilitiesSchema.js";
import type * as capabilityBindings from "../capabilityBindings.js";
import type * as capabilityCatalog from "../capabilityCatalog.js";
import type * as capabilityContent from "../capabilityContent.js";
import type * as capabilityState from "../capabilityState.js";
import type * as ccAccountsShared from "../ccAccountsShared.js";
import type * as ccSwitchAhead from "../ccSwitchAhead.js";
import type * as changeFeed from "../changeFeed.js";
import type * as changeLog from "../changeLog.js";
import type * as changes from "../changes.js";
import type * as changesDeploy from "../changesDeploy.js";
import type * as changesProse from "../changesProse.js";
import type * as changesQueries from "../changesQueries.js";
import type * as changesSchedule from "../changesSchedule.js";
import type * as changesWeek from "../changesWeek.js";
import type * as chat from "../chat.js";
import type * as chatAccess from "../chatAccess.js";
import type * as chatText from "../chatText.js";
import type * as chatTyping from "../chatTyping.js";
import type * as cleanup from "../cleanup.js";
import type * as cliAuth from "../cliAuth.js";
import type * as client_state from "../client_state.js";
import type * as cloud from "../cloud.js";
import type * as cloudPlacement from "../cloudPlacement.js";
import type * as cloudWake from "../cloudWake.js";
import type * as cloudWakeAws from "../cloudWakeAws.js";
import type * as codeComments from "../codeComments.js";
import type * as collab from "../collab.js";
import type * as commentViewWrites from "../commentViewWrites.js";
import type * as comments from "../comments.js";
import type * as commits from "../commits.js";
import type * as composerSuggestions from "../composerSuggestions.js";
import type * as conversationLinks from "../conversationLinks.js";
import type * as conversationSafety from "../conversationSafety.js";
import type * as conversationSessionLookup from "../conversationSessionLookup.js";
import type * as conversations from "../conversations.js";
import type * as counters from "../counters.js";
import type * as crons from "../crons.js";
import type * as daemonCommandUtils from "../daemonCommandUtils.js";
import type * as daemonLogs from "../daemonLogs.js";
import type * as data from "../data.js";
import type * as debugTmp from "../debugTmp.js";
import type * as debugTmpDiet from "../debugTmpDiet.js";
import type * as decisionStacks from "../decisionStacks.js";
import type * as decisions from "../decisions.js";
import type * as deviceRouting from "../deviceRouting.js";
import type * as deviceSettingsShared from "../deviceSettingsShared.js";
import type * as devices from "../devices.js";
import type * as dispatch from "../dispatch.js";
import type * as docExtraction from "../docExtraction.js";
import type * as docLab from "../docLab.js";
import type * as docSync from "../docSync.js";
import type * as docs from "../docs.js";
import type * as dormancy from "../dormancy.js";
import type * as emails_digest from "../emails/digest.js";
import type * as emails_render from "../emails/render.js";
import type * as emails_send from "../emails/send.js";
import type * as emails_templates from "../emails/templates.js";
import type * as entities from "../entities.js";
import type * as executionBindings from "../executionBindings.js";
import type * as expectations from "../expectations.js";
import type * as expectationsSchema from "../expectationsSchema.js";
import type * as externalEvents from "../externalEvents.js";
import type * as favoriteViewWrites from "../favoriteViewWrites.js";
import type * as feedPagination from "../feedPagination.js";
import type * as fileChangeBodies from "../fileChangeBodies.js";
import type * as fileChanges_applyPatchParser from "../fileChanges/applyPatchParser.js";
import type * as fileChanges_embeddedPatch from "../fileChanges/embeddedPatch.js";
import type * as fileChanges_extractor from "../fileChanges/extractor.js";
import type * as fileChanges_patchParser from "../fileChanges/patchParser.js";
import type * as fileChanges_unifiedDiffParser from "../fileChanges/unifiedDiffParser.js";
import type * as fileTouches from "../fileTouches.js";
import type * as follow from "../follow.js";
import type * as forkCopy from "../forkCopy.js";
import type * as functions from "../functions.js";
import type * as gitActivity from "../gitActivity.js";
import type * as githubApi from "../githubApi.js";
import type * as githubApp from "../githubApp.js";
import type * as githubIssuesApi from "../githubIssuesApi.js";
import type * as githubWebhooks from "../githubWebhooks.js";
import type * as goals from "../goals.js";
import type * as googleOAuth from "../googleOAuth.js";
import type * as googleOAuthSchema from "../googleOAuthSchema.js";
import type * as handoff from "../handoff.js";
import type * as harnessChanges from "../harnessChanges.js";
import type * as health from "../health.js";
import type * as heartbeatBacklog from "../heartbeatBacklog.js";
import type * as hostedReplay from "../hostedReplay.js";
import type * as htmlEscape from "../htmlEscape.js";
import type * as http from "../http.js";
import type * as huddleBackfill from "../huddleBackfill.js";
import type * as idleSummary from "../idleSummary.js";
import type * as images from "../images.js";
import type * as inboxFilters from "../inboxFilters.js";
import type * as inboxHides from "../inboxHides.js";
import type * as inboxProjection from "../inboxProjection.js";
import type * as ingest from "../ingest.js";
import type * as ingestHttp from "../ingestHttp.js";
import type * as ingestSchema from "../ingestSchema.js";
import type * as initiatives from "../initiatives.js";
import type * as integrations from "../integrations.js";
import type * as ipRateLimit from "../ipRateLimit.js";
import type * as issueSync from "../issueSync.js";
import type * as issueSyncSchema from "../issueSyncSchema.js";
import type * as lib_access from "../lib/access.js";
import type * as lib_accessKeys from "../lib/accessKeys.js";
import type * as lib_activityPunchcard from "../lib/activityPunchcard.js";
import type * as lib_actor from "../lib/actor.js";
import type * as lib_anthropic from "../lib/anthropic.js";
import type * as lib_appSource from "../lib/appSource.js";
import type * as lib_artifactGates from "../lib/artifactGates.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_awsSigV4 from "../lib/awsSigV4.js";
import type * as lib_callGuestAdmission from "../lib/callGuestAdmission.js";
import type * as lib_callRecordingRuns from "../lib/callRecordingRuns.js";
import type * as lib_callValidators from "../lib/callValidators.js";
import type * as lib_castPlayer from "../lib/castPlayer.js";
import type * as lib_changesAccess from "../lib/changesAccess.js";
import type * as lib_changesDirty from "../lib/changesDirty.js";
import type * as lib_changesProseModel from "../lib/changesProseModel.js";
import type * as lib_charterBudget from "../lib/charterBudget.js";
import type * as lib_chatAttachment from "../lib/chatAttachment.js";
import type * as lib_chatQuota from "../lib/chatQuota.js";
import type * as lib_chatWakeIds from "../lib/chatWakeIds.js";
import type * as lib_cliErrorStatus from "../lib/cliErrorStatus.js";
import type * as lib_cloudHostValidators from "../lib/cloudHostValidators.js";
import type * as lib_codecastSigning from "../lib/codecastSigning.js";
import type * as lib_commentSessionInfo from "../lib/commentSessionInfo.js";
import type * as lib_daemonCommandClaim from "../lib/daemonCommandClaim.js";
import type * as lib_decisionAudience from "../lib/decisionAudience.js";
import type * as lib_decisionCategory from "../lib/decisionCategory.js";
import type * as lib_deletedSessions from "../lib/deletedSessions.js";
import type * as lib_displayNames from "../lib/displayNames.js";
import type * as lib_docSnapshot from "../lib/docSnapshot.js";
import type * as lib_eventFilterValidator from "../lib/eventFilterValidator.js";
import type * as lib_expectationsApply from "../lib/expectationsApply.js";
import type * as lib_externalAuthor from "../lib/externalAuthor.js";
import type * as lib_fileChangeBody from "../lib/fileChangeBody.js";
import type * as lib_gitRefs from "../lib/gitRefs.js";
import type * as lib_hash from "../lib/hash.js";
import type * as lib_hmac from "../lib/hmac.js";
import type * as lib_httpRateLimit from "../lib/httpRateLimit.js";
import type * as lib_ingestGroups from "../lib/ingestGroups.js";
import type * as lib_ingestScope from "../lib/ingestScope.js";
import type * as lib_ingestScopeArgs from "../lib/ingestScopeArgs.js";
import type * as lib_initiativeRef from "../lib/initiativeRef.js";
import type * as lib_initiativeValidators from "../lib/initiativeValidators.js";
import type * as lib_issueMapping from "../lib/issueMapping.js";
import type * as lib_lineMerge from "../lib/lineMerge.js";
import type * as lib_linePriority from "../lib/linePriority.js";
import type * as lib_lineProfileValidator from "../lib/lineProfileValidator.js";
import type * as lib_lineWatch from "../lib/lineWatch.js";
import type * as lib_linkPreviewMeta from "../lib/linkPreviewMeta.js";
import type * as lib_liveActivityRefresh from "../lib/liveActivityRefresh.js";
import type * as lib_liveSessions from "../lib/liveSessions.js";
import type * as lib_livekitJwt from "../lib/livekitJwt.js";
import type * as lib_livekitServer from "../lib/livekitServer.js";
import type * as lib_localCommitFiles from "../lib/localCommitFiles.js";
import type * as lib_mentionResolve from "../lib/mentionResolve.js";
import type * as lib_notificationActor from "../lib/notificationActor.js";
import type * as lib_notificationTypes from "../lib/notificationTypes.js";
import type * as lib_openTasksValidator from "../lib/openTasksValidator.js";
import type * as lib_orgAccess from "../lib/orgAccess.js";
import type * as lib_orgActivity from "../lib/orgActivity.js";
import type * as lib_orgAssistant from "../lib/orgAssistant.js";
import type * as lib_orgCaps from "../lib/orgCaps.js";
import type * as lib_orgChangeLog from "../lib/orgChangeLog.js";
import type * as lib_orgCharter from "../lib/orgCharter.js";
import type * as lib_orgCoverage from "../lib/orgCoverage.js";
import type * as lib_orgOwnership from "../lib/orgOwnership.js";
import type * as lib_orgRouter from "../lib/orgRouter.js";
import type * as lib_orgRoutine from "../lib/orgRoutine.js";
import type * as lib_orgScope from "../lib/orgScope.js";
import type * as lib_personLabel from "../lib/personLabel.js";
import type * as lib_prSessions from "../lib/prSessions.js";
import type * as lib_projectRef from "../lib/projectRef.js";
import type * as lib_projectWork from "../lib/projectWork.js";
import type * as lib_publicFetch from "../lib/publicFetch.js";
import type * as lib_r2 from "../lib/r2.js";
import type * as lib_repoSearch from "../lib/repoSearch.js";
import type * as lib_requireUser from "../lib/requireUser.js";
import type * as lib_roleInitiatives from "../lib/roleInitiatives.js";
import type * as lib_rowByRef from "../lib/rowByRef.js";
import type * as lib_sanitize from "../lib/sanitize.js";
import type * as lib_seatKill from "../lib/seatKill.js";
import type * as lib_sessionAsk from "../lib/sessionAsk.js";
import type * as lib_sessionAskCitations from "../lib/sessionAskCitations.js";
import type * as lib_sessionIdentityFields from "../lib/sessionIdentityFields.js";
import type * as lib_sessionMedia from "../lib/sessionMedia.js";
import type * as lib_siteUrl from "../lib/siteUrl.js";
import type * as lib_slackApi from "../lib/slackApi.js";
import type * as lib_slackFiles from "../lib/slackFiles.js";
import type * as lib_slackMirror from "../lib/slackMirror.js";
import type * as lib_slackOutbound from "../lib/slackOutbound.js";
import type * as lib_slackText from "../lib/slackText.js";
import type * as lib_slug from "../lib/slug.js";
import type * as lib_sourceHealth from "../lib/sourceHealth.js";
import type * as lib_standingSeat from "../lib/standingSeat.js";
import type * as lib_taskOwner from "../lib/taskOwner.js";
import type * as lib_taskWrite from "../lib/taskWrite.js";
import type * as lib_teamDay from "../lib/teamDay.js";
import type * as lib_teamFeatureGuard from "../lib/teamFeatureGuard.js";
import type * as lib_tokenHttp from "../lib/tokenHttp.js";
import type * as lib_tokenRefresh from "../lib/tokenRefresh.js";
import type * as lib_triggerMatch from "../lib/triggerMatch.js";
import type * as lib_userSend from "../lib/userSend.js";
import type * as lib_viewWriters from "../lib/viewWriters.js";
import type * as lib_wallet from "../lib/wallet.js";
import type * as lib_whisk from "../lib/whisk.js";
import type * as lineGround from "../lineGround.js";
import type * as lineLearn from "../lineLearn.js";
import type * as lineNotices from "../lineNotices.js";
import type * as linearApi from "../linearApi.js";
import type * as linearWebhooks from "../linearWebhooks.js";
import type * as linkPreviews from "../linkPreviews.js";
import type * as liveActivity from "../liveActivity.js";
import type * as localFirstCommands from "../localFirstCommands.js";
import type * as localViewRevisions from "../localViewRevisions.js";
import type * as loopState from "../loopState.js";
import type * as machineResources from "../machineResources.js";
import type * as machineResourcesSchema from "../machineResourcesSchema.js";
import type * as managedSessions from "../managedSessions.js";
import type * as messageFeed from "../messageFeed.js";
import type * as messageViewContracts from "../messageViewContracts.js";
import type * as messages from "../messages.js";
import type * as metrics from "../metrics.js";
import type * as migrations from "../migrations.js";
import type * as modCalls from "../modCalls.js";
import type * as modLocal from "../modLocal.js";
import type * as modLogs from "../modLogs.js";
import type * as modObjects from "../modObjects.js";
import type * as mods from "../mods.js";
import type * as notificationRouter from "../notificationRouter.js";
import type * as notifications from "../notifications.js";
import type * as oauthConnectors from "../oauthConnectors.js";
import type * as oauthConnectorsSchema from "../oauthConnectorsSchema.js";
import type * as orchestrationEvents from "../orchestrationEvents.js";
import type * as org from "../org.js";
import type * as orgAgenda from "../orgAgenda.js";
import type * as orgAutonomyDefault from "../orgAutonomyDefault.js";
import type * as orgChanges from "../orgChanges.js";
import type * as orgChannels from "../orgChannels.js";
import type * as orgGoals from "../orgGoals.js";
import type * as orgHandoff from "../orgHandoff.js";
import type * as orgHealth from "../orgHealth.js";
import type * as orgInit from "../orgInit.js";
import type * as orgLine from "../orgLine.js";
import type * as orgLineMerge from "../orgLineMerge.js";
import type * as orgProposals from "../orgProposals.js";
import type * as orgRoles from "../orgRoles.js";
import type * as orgRootSeat from "../orgRootSeat.js";
import type * as orgRoute from "../orgRoute.js";
import type * as orgSplit from "../orgSplit.js";
import type * as orgTemplateLearning from "../orgTemplateLearning.js";
import type * as orgTemplates from "../orgTemplates.js";
import type * as orgWatch from "../orgWatch.js";
import type * as orgWhere from "../orgWhere.js";
import type * as pathStats from "../pathStats.js";
import type * as patterns from "../patterns.js";
import type * as pendingMessageWrites from "../pendingMessageWrites.js";
import type * as pendingMessages from "../pendingMessages.js";
import type * as permissions from "../permissions.js";
import type * as plans from "../plans.js";
import type * as prCli from "../prCli.js";
import type * as prDetails from "../prDetails.js";
import type * as prShepherd from "../prShepherd.js";
import type * as presencePolicy from "../presencePolicy.js";
import type * as presenceState from "../presenceState.js";
import type * as principalViewRevisions from "../principalViewRevisions.js";
import type * as privacy from "../privacy.js";
import type * as progressEvents from "../progressEvents.js";
import type * as projectPaths from "../projectPaths.js";
import type * as projectUpdates from "../projectUpdates.js";
import type * as projects from "../projects.js";
import type * as publicComments from "../publicComments.js";
import type * as publicShare from "../publicShare.js";
import type * as pull_requests from "../pull_requests.js";
import type * as pushRouter from "../pushRouter.js";
import type * as rateLimit from "../rateLimit.js";
import type * as redact from "../redact.js";
import type * as replays from "../replays.js";
import type * as replaysHttp from "../replaysHttp.js";
import type * as repoPublicHttp from "../repoPublicHttp.js";
import type * as repoSessions from "../repoSessions.js";
import type * as repos from "../repos.js";
import type * as resourceOffload from "../resourceOffload.js";
import type * as resourceOffloadSchema from "../resourceOffloadSchema.js";
import type * as reviewNotes from "../reviewNotes.js";
import type * as reviews from "../reviews.js";
import type * as savedViews from "../savedViews.js";
import type * as searchCore from "../searchCore.js";
import type * as searchMirror from "../searchMirror.js";
import type * as sendBackfill from "../sendBackfill.js";
import type * as sessionAsk from "../sessionAsk.js";
import type * as sessionAssignmentNotifications from "../sessionAssignmentNotifications.js";
import type * as sessionCommands from "../sessionCommands.js";
import type * as sessionDecisions from "../sessionDecisions.js";
import type * as sessionDelete from "../sessionDelete.js";
import type * as sessionImages from "../sessionImages.js";
import type * as sessionInitiator from "../sessionInitiator.js";
import type * as sessionInsights from "../sessionInsights.js";
import type * as sessionLaunch from "../sessionLaunch.js";
import type * as sessionMigrations from "../sessionMigrations.js";
import type * as sessionOwners from "../sessionOwners.js";
import type * as sessionOwnership from "../sessionOwnership.js";
import type * as sessionQueryCore from "../sessionQueryCore.js";
import type * as sessionQuerySearch from "../sessionQuerySearch.js";
import type * as sessionQuerySuggest from "../sessionQuerySuggest.js";
import type * as sessionReads from "../sessionReads.js";
import type * as sessionRelease from "../sessionRelease.js";
import type * as sessionThreads from "../sessionThreads.js";
import type * as signals from "../signals.js";
import type * as slack from "../slack.js";
import type * as slackSync from "../slackSync.js";
import type * as smallViewContracts from "../smallViewContracts.js";
import type * as sources_app from "../sources/app.js";
import type * as sources_posthog from "../sources/posthog.js";
import type * as sources_sentry from "../sources/sentry.js";
import type * as sources_vendorReplay from "../sources/vendorReplay.js";
import type * as spawn from "../spawn.js";
import type * as storyMode from "../storyMode.js";
import type * as syncCursors from "../syncCursors.js";
import type * as syncLog from "../syncLog.js";
import type * as syncLogPrune from "../syncLogPrune.js";
import type * as syncOutbox from "../syncOutbox.js";
import type * as syncOutboxSchema from "../syncOutboxSchema.js";
import type * as syncOutboxWriter from "../syncOutboxWriter.js";
import type * as systemConfig from "../systemConfig.js";
import type * as taskCommentRepair from "../taskCommentRepair.js";
import type * as taskEvidence from "../taskEvidence.js";
import type * as taskMining from "../taskMining.js";
import type * as tasks from "../tasks.js";
import type * as teamActivity from "../teamActivity.js";
import type * as teamFeatures from "../teamFeatures.js";
import type * as teamScopeSweep from "../teamScopeSweep.js";
import type * as teamVisibility from "../teamVisibility.js";
import type * as teams from "../teams.js";
import type * as terminalStream from "../terminalStream.js";
import type * as testDb from "../testDb.js";
import type * as threadMembershipSweep from "../threadMembershipSweep.js";
import type * as threadReads from "../threadReads.js";
import type * as threads from "../threads.js";
import type * as titleGeneration from "../titleGeneration.js";
import type * as tokenConnectors from "../tokenConnectors.js";
import type * as tokenSpend from "../tokenSpend.js";
import type * as transcripts from "../transcripts.js";
import type * as usageCalibration from "../usageCalibration.js";
import type * as userMessagesFilter from "../userMessagesFilter.js";
import type * as userSends from "../userSends.js";
import type * as users from "../users.js";
import type * as vaultMirror from "../vaultMirror.js";
import type * as verification from "../verification.js";
import type * as wakeCost from "../wakeCost.js";
import type * as wallet from "../wallet.js";
import type * as webDocsPagination from "../webDocsPagination.js";
import type * as whisk from "../whisk.js";
import type * as workerSettle from "../workerSettle.js";
import type * as workflow_runs from "../workflow_runs.js";
import type * as workflows from "../workflows.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  accountSwitch: typeof accountSwitch;
  admin_mergeUser: typeof admin_mergeUser;
  agentDefinitions: typeof agentDefinitions;
  agentPromptRepair: typeof agentPromptRepair;
  agentSchema: typeof agentSchema;
  agentTasks: typeof agentTasks;
  analytics: typeof analytics;
  anchors: typeof anchors;
  apiTokens: typeof apiTokens;
  apns: typeof apns;
  apnsProviderToken: typeof apnsProviderToken;
  apnsVoip: typeof apnsVoip;
  appConnections: typeof appConnections;
  artifactMarkdown: typeof artifactMarkdown;
  artifactPages: typeof artifactPages;
  artifacts: typeof artifacts;
  artifactsHttp: typeof artifactsHttp;
  "assistant/entry": typeof assistant_entry;
  "assistant/history": typeof assistant_history;
  "assistant/input": typeof assistant_input;
  "assistant/routines": typeof assistant_routines;
  "assistant/tools/codecast": typeof assistant_tools_codecast;
  "assistant/tools/index": typeof assistant_tools_index;
  "assistant/tools/web": typeof assistant_tools_web;
  "assistant/tools/workspace": typeof assistant_tools_workspace;
  "assistant/turns": typeof assistant_turns;
  assistantSchema: typeof assistantSchema;
  auth: typeof auth;
  billing: typeof billing;
  blame: typeof blame;
  blameCore: typeof blameCore;
  bookmarkViewWrites: typeof bookmarkViewWrites;
  bookmarks: typeof bookmarks;
  buckets: typeof buckets;
  callChat: typeof callChat;
  callFace: typeof callFace;
  callGuests: typeof callGuests;
  callRecordings: typeof callRecordings;
  callRooms: typeof callRooms;
  calls: typeof calls;
  capabilities: typeof capabilities;
  capabilitiesSchema: typeof capabilitiesSchema;
  capabilityBindings: typeof capabilityBindings;
  capabilityCatalog: typeof capabilityCatalog;
  capabilityContent: typeof capabilityContent;
  capabilityState: typeof capabilityState;
  ccAccountsShared: typeof ccAccountsShared;
  ccSwitchAhead: typeof ccSwitchAhead;
  changeFeed: typeof changeFeed;
  changeLog: typeof changeLog;
  changes: typeof changes;
  changesDeploy: typeof changesDeploy;
  changesProse: typeof changesProse;
  changesQueries: typeof changesQueries;
  changesSchedule: typeof changesSchedule;
  changesWeek: typeof changesWeek;
  chat: typeof chat;
  chatAccess: typeof chatAccess;
  chatText: typeof chatText;
  chatTyping: typeof chatTyping;
  cleanup: typeof cleanup;
  cliAuth: typeof cliAuth;
  client_state: typeof client_state;
  cloud: typeof cloud;
  cloudPlacement: typeof cloudPlacement;
  cloudWake: typeof cloudWake;
  cloudWakeAws: typeof cloudWakeAws;
  codeComments: typeof codeComments;
  collab: typeof collab;
  commentViewWrites: typeof commentViewWrites;
  comments: typeof comments;
  commits: typeof commits;
  composerSuggestions: typeof composerSuggestions;
  conversationLinks: typeof conversationLinks;
  conversationSafety: typeof conversationSafety;
  conversationSessionLookup: typeof conversationSessionLookup;
  conversations: typeof conversations;
  counters: typeof counters;
  crons: typeof crons;
  daemonCommandUtils: typeof daemonCommandUtils;
  daemonLogs: typeof daemonLogs;
  data: typeof data;
  debugTmp: typeof debugTmp;
  debugTmpDiet: typeof debugTmpDiet;
  decisionStacks: typeof decisionStacks;
  decisions: typeof decisions;
  deviceRouting: typeof deviceRouting;
  deviceSettingsShared: typeof deviceSettingsShared;
  devices: typeof devices;
  dispatch: typeof dispatch;
  docExtraction: typeof docExtraction;
  docLab: typeof docLab;
  docSync: typeof docSync;
  docs: typeof docs;
  dormancy: typeof dormancy;
  "emails/digest": typeof emails_digest;
  "emails/render": typeof emails_render;
  "emails/send": typeof emails_send;
  "emails/templates": typeof emails_templates;
  entities: typeof entities;
  executionBindings: typeof executionBindings;
  expectations: typeof expectations;
  expectationsSchema: typeof expectationsSchema;
  externalEvents: typeof externalEvents;
  favoriteViewWrites: typeof favoriteViewWrites;
  feedPagination: typeof feedPagination;
  fileChangeBodies: typeof fileChangeBodies;
  "fileChanges/applyPatchParser": typeof fileChanges_applyPatchParser;
  "fileChanges/embeddedPatch": typeof fileChanges_embeddedPatch;
  "fileChanges/extractor": typeof fileChanges_extractor;
  "fileChanges/patchParser": typeof fileChanges_patchParser;
  "fileChanges/unifiedDiffParser": typeof fileChanges_unifiedDiffParser;
  fileTouches: typeof fileTouches;
  follow: typeof follow;
  forkCopy: typeof forkCopy;
  functions: typeof functions;
  gitActivity: typeof gitActivity;
  githubApi: typeof githubApi;
  githubApp: typeof githubApp;
  githubIssuesApi: typeof githubIssuesApi;
  githubWebhooks: typeof githubWebhooks;
  goals: typeof goals;
  googleOAuth: typeof googleOAuth;
  googleOAuthSchema: typeof googleOAuthSchema;
  handoff: typeof handoff;
  harnessChanges: typeof harnessChanges;
  health: typeof health;
  heartbeatBacklog: typeof heartbeatBacklog;
  hostedReplay: typeof hostedReplay;
  htmlEscape: typeof htmlEscape;
  http: typeof http;
  huddleBackfill: typeof huddleBackfill;
  idleSummary: typeof idleSummary;
  images: typeof images;
  inboxFilters: typeof inboxFilters;
  inboxHides: typeof inboxHides;
  inboxProjection: typeof inboxProjection;
  ingest: typeof ingest;
  ingestHttp: typeof ingestHttp;
  ingestSchema: typeof ingestSchema;
  initiatives: typeof initiatives;
  integrations: typeof integrations;
  ipRateLimit: typeof ipRateLimit;
  issueSync: typeof issueSync;
  issueSyncSchema: typeof issueSyncSchema;
  "lib/access": typeof lib_access;
  "lib/accessKeys": typeof lib_accessKeys;
  "lib/activityPunchcard": typeof lib_activityPunchcard;
  "lib/actor": typeof lib_actor;
  "lib/anthropic": typeof lib_anthropic;
  "lib/appSource": typeof lib_appSource;
  "lib/artifactGates": typeof lib_artifactGates;
  "lib/auth": typeof lib_auth;
  "lib/awsSigV4": typeof lib_awsSigV4;
  "lib/callGuestAdmission": typeof lib_callGuestAdmission;
  "lib/callRecordingRuns": typeof lib_callRecordingRuns;
  "lib/callValidators": typeof lib_callValidators;
  "lib/castPlayer": typeof lib_castPlayer;
  "lib/changesAccess": typeof lib_changesAccess;
  "lib/changesDirty": typeof lib_changesDirty;
  "lib/changesProseModel": typeof lib_changesProseModel;
  "lib/charterBudget": typeof lib_charterBudget;
  "lib/chatAttachment": typeof lib_chatAttachment;
  "lib/chatQuota": typeof lib_chatQuota;
  "lib/chatWakeIds": typeof lib_chatWakeIds;
  "lib/cliErrorStatus": typeof lib_cliErrorStatus;
  "lib/cloudHostValidators": typeof lib_cloudHostValidators;
  "lib/codecastSigning": typeof lib_codecastSigning;
  "lib/commentSessionInfo": typeof lib_commentSessionInfo;
  "lib/daemonCommandClaim": typeof lib_daemonCommandClaim;
  "lib/decisionAudience": typeof lib_decisionAudience;
  "lib/decisionCategory": typeof lib_decisionCategory;
  "lib/deletedSessions": typeof lib_deletedSessions;
  "lib/displayNames": typeof lib_displayNames;
  "lib/docSnapshot": typeof lib_docSnapshot;
  "lib/eventFilterValidator": typeof lib_eventFilterValidator;
  "lib/expectationsApply": typeof lib_expectationsApply;
  "lib/externalAuthor": typeof lib_externalAuthor;
  "lib/fileChangeBody": typeof lib_fileChangeBody;
  "lib/gitRefs": typeof lib_gitRefs;
  "lib/hash": typeof lib_hash;
  "lib/hmac": typeof lib_hmac;
  "lib/httpRateLimit": typeof lib_httpRateLimit;
  "lib/ingestGroups": typeof lib_ingestGroups;
  "lib/ingestScope": typeof lib_ingestScope;
  "lib/ingestScopeArgs": typeof lib_ingestScopeArgs;
  "lib/initiativeRef": typeof lib_initiativeRef;
  "lib/initiativeValidators": typeof lib_initiativeValidators;
  "lib/issueMapping": typeof lib_issueMapping;
  "lib/lineMerge": typeof lib_lineMerge;
  "lib/linePriority": typeof lib_linePriority;
  "lib/lineProfileValidator": typeof lib_lineProfileValidator;
  "lib/lineWatch": typeof lib_lineWatch;
  "lib/linkPreviewMeta": typeof lib_linkPreviewMeta;
  "lib/liveActivityRefresh": typeof lib_liveActivityRefresh;
  "lib/liveSessions": typeof lib_liveSessions;
  "lib/livekitJwt": typeof lib_livekitJwt;
  "lib/livekitServer": typeof lib_livekitServer;
  "lib/localCommitFiles": typeof lib_localCommitFiles;
  "lib/mentionResolve": typeof lib_mentionResolve;
  "lib/notificationActor": typeof lib_notificationActor;
  "lib/notificationTypes": typeof lib_notificationTypes;
  "lib/openTasksValidator": typeof lib_openTasksValidator;
  "lib/orgAccess": typeof lib_orgAccess;
  "lib/orgActivity": typeof lib_orgActivity;
  "lib/orgAssistant": typeof lib_orgAssistant;
  "lib/orgCaps": typeof lib_orgCaps;
  "lib/orgChangeLog": typeof lib_orgChangeLog;
  "lib/orgCharter": typeof lib_orgCharter;
  "lib/orgCoverage": typeof lib_orgCoverage;
  "lib/orgOwnership": typeof lib_orgOwnership;
  "lib/orgRouter": typeof lib_orgRouter;
  "lib/orgRoutine": typeof lib_orgRoutine;
  "lib/orgScope": typeof lib_orgScope;
  "lib/personLabel": typeof lib_personLabel;
  "lib/prSessions": typeof lib_prSessions;
  "lib/projectRef": typeof lib_projectRef;
  "lib/projectWork": typeof lib_projectWork;
  "lib/publicFetch": typeof lib_publicFetch;
  "lib/r2": typeof lib_r2;
  "lib/repoSearch": typeof lib_repoSearch;
  "lib/requireUser": typeof lib_requireUser;
  "lib/roleInitiatives": typeof lib_roleInitiatives;
  "lib/rowByRef": typeof lib_rowByRef;
  "lib/sanitize": typeof lib_sanitize;
  "lib/seatKill": typeof lib_seatKill;
  "lib/sessionAsk": typeof lib_sessionAsk;
  "lib/sessionAskCitations": typeof lib_sessionAskCitations;
  "lib/sessionIdentityFields": typeof lib_sessionIdentityFields;
  "lib/sessionMedia": typeof lib_sessionMedia;
  "lib/siteUrl": typeof lib_siteUrl;
  "lib/slackApi": typeof lib_slackApi;
  "lib/slackFiles": typeof lib_slackFiles;
  "lib/slackMirror": typeof lib_slackMirror;
  "lib/slackOutbound": typeof lib_slackOutbound;
  "lib/slackText": typeof lib_slackText;
  "lib/slug": typeof lib_slug;
  "lib/sourceHealth": typeof lib_sourceHealth;
  "lib/standingSeat": typeof lib_standingSeat;
  "lib/taskOwner": typeof lib_taskOwner;
  "lib/taskWrite": typeof lib_taskWrite;
  "lib/teamDay": typeof lib_teamDay;
  "lib/teamFeatureGuard": typeof lib_teamFeatureGuard;
  "lib/tokenHttp": typeof lib_tokenHttp;
  "lib/tokenRefresh": typeof lib_tokenRefresh;
  "lib/triggerMatch": typeof lib_triggerMatch;
  "lib/userSend": typeof lib_userSend;
  "lib/viewWriters": typeof lib_viewWriters;
  "lib/wallet": typeof lib_wallet;
  "lib/whisk": typeof lib_whisk;
  lineGround: typeof lineGround;
  lineLearn: typeof lineLearn;
  lineNotices: typeof lineNotices;
  linearApi: typeof linearApi;
  linearWebhooks: typeof linearWebhooks;
  linkPreviews: typeof linkPreviews;
  liveActivity: typeof liveActivity;
  localFirstCommands: typeof localFirstCommands;
  localViewRevisions: typeof localViewRevisions;
  loopState: typeof loopState;
  machineResources: typeof machineResources;
  machineResourcesSchema: typeof machineResourcesSchema;
  managedSessions: typeof managedSessions;
  messageFeed: typeof messageFeed;
  messageViewContracts: typeof messageViewContracts;
  messages: typeof messages;
  metrics: typeof metrics;
  migrations: typeof migrations;
  modCalls: typeof modCalls;
  modLocal: typeof modLocal;
  modLogs: typeof modLogs;
  modObjects: typeof modObjects;
  mods: typeof mods;
  notificationRouter: typeof notificationRouter;
  notifications: typeof notifications;
  oauthConnectors: typeof oauthConnectors;
  oauthConnectorsSchema: typeof oauthConnectorsSchema;
  orchestrationEvents: typeof orchestrationEvents;
  org: typeof org;
  orgAgenda: typeof orgAgenda;
  orgAutonomyDefault: typeof orgAutonomyDefault;
  orgChanges: typeof orgChanges;
  orgChannels: typeof orgChannels;
  orgGoals: typeof orgGoals;
  orgHandoff: typeof orgHandoff;
  orgHealth: typeof orgHealth;
  orgInit: typeof orgInit;
  orgLine: typeof orgLine;
  orgLineMerge: typeof orgLineMerge;
  orgProposals: typeof orgProposals;
  orgRoles: typeof orgRoles;
  orgRootSeat: typeof orgRootSeat;
  orgRoute: typeof orgRoute;
  orgSplit: typeof orgSplit;
  orgTemplateLearning: typeof orgTemplateLearning;
  orgTemplates: typeof orgTemplates;
  orgWatch: typeof orgWatch;
  orgWhere: typeof orgWhere;
  pathStats: typeof pathStats;
  patterns: typeof patterns;
  pendingMessageWrites: typeof pendingMessageWrites;
  pendingMessages: typeof pendingMessages;
  permissions: typeof permissions;
  plans: typeof plans;
  prCli: typeof prCli;
  prDetails: typeof prDetails;
  prShepherd: typeof prShepherd;
  presencePolicy: typeof presencePolicy;
  presenceState: typeof presenceState;
  principalViewRevisions: typeof principalViewRevisions;
  privacy: typeof privacy;
  progressEvents: typeof progressEvents;
  projectPaths: typeof projectPaths;
  projectUpdates: typeof projectUpdates;
  projects: typeof projects;
  publicComments: typeof publicComments;
  publicShare: typeof publicShare;
  pull_requests: typeof pull_requests;
  pushRouter: typeof pushRouter;
  rateLimit: typeof rateLimit;
  redact: typeof redact;
  replays: typeof replays;
  replaysHttp: typeof replaysHttp;
  repoPublicHttp: typeof repoPublicHttp;
  repoSessions: typeof repoSessions;
  repos: typeof repos;
  resourceOffload: typeof resourceOffload;
  resourceOffloadSchema: typeof resourceOffloadSchema;
  reviewNotes: typeof reviewNotes;
  reviews: typeof reviews;
  savedViews: typeof savedViews;
  searchCore: typeof searchCore;
  searchMirror: typeof searchMirror;
  sendBackfill: typeof sendBackfill;
  sessionAsk: typeof sessionAsk;
  sessionAssignmentNotifications: typeof sessionAssignmentNotifications;
  sessionCommands: typeof sessionCommands;
  sessionDecisions: typeof sessionDecisions;
  sessionDelete: typeof sessionDelete;
  sessionImages: typeof sessionImages;
  sessionInitiator: typeof sessionInitiator;
  sessionInsights: typeof sessionInsights;
  sessionLaunch: typeof sessionLaunch;
  sessionMigrations: typeof sessionMigrations;
  sessionOwners: typeof sessionOwners;
  sessionOwnership: typeof sessionOwnership;
  sessionQueryCore: typeof sessionQueryCore;
  sessionQuerySearch: typeof sessionQuerySearch;
  sessionQuerySuggest: typeof sessionQuerySuggest;
  sessionReads: typeof sessionReads;
  sessionRelease: typeof sessionRelease;
  sessionThreads: typeof sessionThreads;
  signals: typeof signals;
  slack: typeof slack;
  slackSync: typeof slackSync;
  smallViewContracts: typeof smallViewContracts;
  "sources/app": typeof sources_app;
  "sources/posthog": typeof sources_posthog;
  "sources/sentry": typeof sources_sentry;
  "sources/vendorReplay": typeof sources_vendorReplay;
  spawn: typeof spawn;
  storyMode: typeof storyMode;
  syncCursors: typeof syncCursors;
  syncLog: typeof syncLog;
  syncLogPrune: typeof syncLogPrune;
  syncOutbox: typeof syncOutbox;
  syncOutboxSchema: typeof syncOutboxSchema;
  syncOutboxWriter: typeof syncOutboxWriter;
  systemConfig: typeof systemConfig;
  taskCommentRepair: typeof taskCommentRepair;
  taskEvidence: typeof taskEvidence;
  taskMining: typeof taskMining;
  tasks: typeof tasks;
  teamActivity: typeof teamActivity;
  teamFeatures: typeof teamFeatures;
  teamScopeSweep: typeof teamScopeSweep;
  teamVisibility: typeof teamVisibility;
  teams: typeof teams;
  terminalStream: typeof terminalStream;
  testDb: typeof testDb;
  threadMembershipSweep: typeof threadMembershipSweep;
  threadReads: typeof threadReads;
  threads: typeof threads;
  titleGeneration: typeof titleGeneration;
  tokenConnectors: typeof tokenConnectors;
  tokenSpend: typeof tokenSpend;
  transcripts: typeof transcripts;
  usageCalibration: typeof usageCalibration;
  userMessagesFilter: typeof userMessagesFilter;
  userSends: typeof userSends;
  users: typeof users;
  vaultMirror: typeof vaultMirror;
  verification: typeof verification;
  wakeCost: typeof wakeCost;
  wallet: typeof wallet;
  webDocsPagination: typeof webDocsPagination;
  whisk: typeof whisk;
  workerSettle: typeof workerSettle;
  workflow_runs: typeof workflow_runs;
  workflows: typeof workflows;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
