// Bundles the runtime SDK (runtime/sdk.ts) into one browser module and writes
// it to convex/lib/sdk.generated.ts, where the HTTP router serves it from.
// React stays external: apps resolve it through the version's import map, so
// the app and the SDK share one React. Run after changing anything under
// runtime/; sdk.test.ts fails while the generated file is stale.
//
//   bun scripts/build-sdk.ts           write the bundle
//   bun scripts/build-sdk.ts --check   exit 1 if the written bundle is stale
import { join } from "node:path";
import { CONVEX_URL_PLACEHOLDER } from "../convex/lib/runtime";
import { sha256Hex } from "../convex/lib/identity";

const ROOT = join(import.meta.dir, "..");
export const GENERATED_PATH = join(ROOT, "convex/lib/sdk.generated.ts");

export async function bundleSdk(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [join(ROOT, "runtime/sdk.ts")],
    target: "browser",
    format: "esm",
    minify: true,
    external: ["react"],
    define: { "process.env.PLAYGROUND_CONVEX_URL": JSON.stringify(CONVEX_URL_PLACEHOLDER) },
  });
  if (!result.success) throw new AggregateError(result.logs, "SDK bundle failed");
  const code = await result.outputs[0].text();
  const placeholders = code.split(CONVEX_URL_PLACEHOLDER).length - 1;
  if (placeholders !== 1) throw new Error(`the bundle holds ${placeholders} Convex URL placeholders; expected 1`);
  return code;
}

export async function generatedSource(): Promise<string> {
  const code = await bundleSdk();
  return `// Generated by scripts/build-sdk.ts from runtime/sdk.ts. Do not edit.
export const SDK_BUNDLE_HASH = ${JSON.stringify((await sha256Hex(code)).slice(0, 32))};
export const SDK_BUNDLE: string = ${JSON.stringify(code)};
`;
}

if (import.meta.main) {
  const next = await generatedSource();
  const file = Bun.file(GENERATED_PATH);
  const current = (await file.exists()) ? await file.text() : "";
  if (process.argv.includes("--check")) {
    if (current !== next) {
      console.error("convex/lib/sdk.generated.ts is stale: run bun scripts/build-sdk.ts");
      process.exit(1);
    }
  } else if (current !== next) {
    await Bun.write(GENERATED_PATH, next);
    console.log(`wrote ${GENERATED_PATH} (${(next.length / 1000).toFixed(1)} KB)`);
  } else {
    console.log("SDK bundle is current");
  }
}
