"use client";

import { useMemo } from "react";
import { TaskSessionRow, type TaskLinkedSession } from "./tasks/TaskSessionList";
import { useCoarseNow } from "../hooks/useCoarseNow";
import { useOpenLinkedSession } from "../hooks/useOpenLinkedSession";
import { useInboxStore } from "../store/inboxStore";

/**
 * The session a plan came out of (plans.created_from_conversation_id), as the
 * first thing under the title. webGet's `sessions` join carries it once the
 * query lands; before that the cached plan row still names the id, and a
 * session the store already holds paints from there.
 */
export function PlanOriginSession({ plan, className = "" }: { plan: any; className?: string }) {
  const originId: string | undefined = plan?.created_from_conversation_id
    ? String(plan.created_from_conversation_id)
    : undefined;
  const now = useCoarseNow(30_000);
  const onOpen = useOpenLinkedSession();
  const inStore = useInboxStore((s) => !!originId && !!s.sessions[originId]);
  const joined: TaskLinkedSession | undefined = useMemo(
    () => (plan?.sessions || []).find((c: any) => String(c._id) === originId),
    [plan?.sessions, originId],
  );
  const snapshot = useMemo(
    () => joined ?? (inStore && originId ? { _id: originId } : null),
    [joined, inStore, originId],
  );

  if (!originId) return null;
  // `sessions` is absent while only the cached row paints; an answer without
  // the origin in it means this viewer cannot open that session.
  if (!snapshot && !Array.isArray(plan?.sessions)) return null;

  return (
    <div className={className}>
      <div className="text-xs font-medium text-sol-text-dim mb-1">Generated by</div>
      {snapshot ? (
        <div className="rounded-md border border-sol-violet/25 bg-sol-violet/[0.04] overflow-hidden">
          <TaskSessionRow snapshot={snapshot} onOpen={onOpen} now={now} prominent />
        </div>
      ) : (
        <div className="rounded-md border border-sol-border/30 px-3 py-2 text-xs text-sol-text-dim">
          A session you do not have access to
        </div>
      )}
    </div>
  );
}
