import type { Release } from "./changelogData";

export const RELEASES_2026_AUG_SEP: Release[] = [
  {
    id: "2026-09",
    month: "September 2026",
    sortDate: "2026-09-01",
    version: "v1.1.114 – v1.1.143",
    desktop: "Desktop v1.1.112",
    tag: "Latest",
    headline: "The org, pull requests, and sessions in the cloud",
    summary:
      "This month codecast got a shape for standing work. A role sits in an org tree and holds a responsibility after any one session ends, so a task or a mention goes to the role and not to whoever happens to be running. Pull requests and issues became objects that a session owns and answers. Sessions start on a cloud host with one flag, idle ones hibernate, and `cast browser` moved into your own Chrome.",
    sections: [
      {
        title: "The org: roles that outlive sessions",
        accent: "violet",
        icon: "Network",
        when: "Sep 13 to 18",
        items: [
          "A role is a seat in an org tree with a scope, a standing brief and a standing session. The session ends and the role stays, so work routes to the responsibility.",
          "Assign a task to a role, or mention its handle in team chat, and the role's session wakes to act on it.",
          "`cast org init` reads the code and your sessions before it proposes seats. You edit the proposal in plain words, then accept it. Templates hire a common role in one step.",
          "The org page draws people and agents in one tree. Each scope page shows the role's brief, its tasks and its recent sessions.",
        ],
        docs: [{ href: "/documentation/org-roles", label: "The org" }],
      },
      {
        title: "Pull requests and issues join the board",
        accent: "blue",
        icon: "GitPullRequest",
        when: "Sep 4 to 14",
        items: [
          "A pull request is now a codecast object. It carries its checks, its reviews and open threads, and the session that owns it until it merges.",
          "`cast pr shepherd on` binds a session to a pull request. A review, a failing check or a merge conflict wakes it, and a submitted review arrives as one message.",
          "Review from the shell: hold a note on each line with `cast pr comment --hold`, then send the batch as one review with one verdict.",
          "Linear teams and GitHub repos import as projects, and their issues become tasks. The sync runs both ways: a task comment posts to the issue, and `cast task done` closes it.",
          "A Code page browses repository files, commits and pull requests, and git and issue events appear in project timelines.",
        ],
        docs: [{ href: "/documentation/pull-requests", label: "Pull requests and issues" }],
      },
      {
        title: "Cloud sessions and a fleet that sleeps",
        accent: "cyan",
        icon: "Cloud",
        when: "Sep 4 to 17",
        items: [
          "`cast spawn --cloud` starts a session on a cloud host in its own worktree, with your local agent settings mirrored to the host.",
          "`cast hibernate` parks an idle session and `cast wake` brings it back. An optional fleet cap and idle bar do the same for a whole machine.",
          "Select several inbox cards to move sessions between your laptop and the cloud in bulk. The transcript marks the point where a session changed machine.",
          "A trigger bound to a cloud host wakes the host before it runs.",
        ],
        docs: [{ href: "/documentation/remote-and-cloud-sessions", label: "Remote and cloud sessions" }],
      },
      {
        title: "cast browser moves into your Chrome",
        accent: "orange",
        icon: "Chrome",
        when: "Sep 2 to 18",
        items: [
          "Once the codecast extension is paired, `cast browser` drives your own Chrome and uses the logins you already have. A separate agent browser needs your explicit permission.",
          "Each session owns one background tab inside a `Cast` tab group, with a colored frame and a pointer that follows the agent's mouse.",
          "An agent can offer a page as a pane beside the conversation with `cast browser pane`. The desktop app shows pages that refuse to be framed in a native pane.",
          "A failing step prints console errors, failed requests and a screenshot into the thread, and a step that runs long says what it waits on.",
        ],
        docs: [{ href: "/documentation/browser", label: "cast browser" }],
      },
      {
        title: "cast computer: native Mac apps",
        accent: "magenta",
        icon: "MousePointerClick",
        when: "Sep 7",
        items: [
          "`cast computer` reads one window of a macOS app as an indexed accessibility tree and acts on one element by its index.",
          "Every action reports whether the change was read back. Exit 0 means the action was delivered; `verified` means the app took it.",
          "`set-value` and a press on an element work on a window in the background, so the agent takes nothing from your screen. No verb raises a window unless you pass `--restore-window`.",
          "Password managers are refused, secure fields render as `[redacted]`, and secrets arrive on stdin so they stay out of shell history.",
        ],
        docs: [{ href: "/documentation/computer", label: "cast computer" }],
      },
      {
        title: "Decisions become documents",
        accent: "yellow",
        icon: "Scale",
        when: "Sep 13 to 15",
        items: [
          "Each decision is now a document with its own page, so it has a link, a history and a place in search.",
          "Related decisions group into a stack that you clear in one sitting. `cast stack reorder` orders it and `cast stack policy --due` gives it a deadline; overdue stacks sort first.",
          "An option can carry its own page with `--option-page`, for a choice that needs a mockup or a report to judge.",
          "The card names the session that asked and where it works, and the server says who may grant the request.",
        ],
        docs: [{ href: "/documentation/decisions", label: "Decisions" }],
      },
      {
        title: "One window syncs, the rest replicate",
        accent: "green",
        icon: "RefreshCw",
        when: "Sep 1 to 3",
        items: [
          "With several windows open, exactly one is elected the sync host. It holds the subscriptions and writes the local cache, and the other windows apply its stream.",
          "Rows from the sync log apply straight into the store. One access rule decides both who receives a row in the log and who may read it in a direct query, so the two cannot disagree.",
          "The sync indicator in the header reads the real distance to the head of the sync log.",
          "The live transcript subscribes to the tail of a conversation, so a long thread streams new messages without loading its first page again.",
        ],
        docs: [{ href: "/documentation/sync-engine", label: "How the client syncs" }],
      },
      {
        title: "Limits pause a session; accounts and agents switch in place",
        accent: "orange",
        icon: "Hourglass",
        when: "Sep 1 to 18",
        items: [
          "Save more than one Claude account and run a session on any of them. When a usage limit lands, codecast recommends the saved account with the most headroom and switches when you approve, or on its own if you turn that on.",
          "A session parked on a limit gets its own card, and continues when the window resets.",
          "Switch a session's agent or model in place, without a new thread. One control panel holds model, switch agent, fork and hand off.",
          "`cast handoff --to` starts a linked session from a short brief of the current one.",
        ],
        docs: [{ href: "/documentation/usage-limits", label: "Usage limits" }],
      },
      {
        title: "Skills, agent definitions, and the line",
        accent: "blue",
        icon: "Sparkles",
        when: "Sep 13 to 14",
        items: [
          "23 `cast-*` skills ship inside the CLI and install as one catalog: pickup, handoff, verify, ship, review, triage, standup and more. Each is a fixed sequence of ordinary `cast` commands.",
          "An agent definition binds a client, a model, an effort, a tool policy and a system prompt under one name. Every launch surface resolves it by name, and definitions appear in the model picker.",
          "Workflow stations run as codecast sessions, and workflow templates ship inside the binary.",
          "A task that a role works needs an independent review to close, and `cast task handoff` carries the evidence to the reviewer.",
        ],
        docs: [
          { href: "/documentation/skills", label: "Skills" },
          { href: "/documentation/workflows", label: "Workflows" },
        ],
      },
      {
        title: "cast check, and a steadier daemon",
        accent: "green",
        icon: "Gauge",
        when: "Sep 4 to 18",
        items: [
          "`cast check` answers every session's typecheck from one shared `tsc --watch` for each tree. Later asks take seconds, and ten sessions asking cost the same as one.",
          "The daemon moved its probe, scan and ingest work to workers, and a watchdog restarts it if its loop hangs.",
          "A message sent into a busy terminal waits for proof that the paste landed once, so a long message no longer splits or sends twice.",
          "`cast status` checks DNS, the backend and latency, with `--json` for scripts.",
        ],
        docs: [{ href: "/documentation/typecheck", label: "cast check" }],
      },
      {
        title: "Triggers you can edit and gate",
        accent: "blue",
        icon: "Clock",
        when: "Sep 1 to 7",
        items: [
          "`cast trigger update` edits a trigger in place. Each edit is a version, and `cast trigger history` shows who changed what.",
          "`--precheck <command>` runs a shell gate before each firing. A gate that fails records a skipped run and spends no session.",
          "Every trigger has a detail page, visible to everyone who can see its session. A spawned run can pin its model.",
          "A stashed session returns to the inbox when a trigger wakes it, and `cast stash --hide` keeps it quiet.",
        ],
        docs: [{ href: "/documentation/triggers", label: "Triggers" }],
      },
      {
        title: "Chat reaches Slack, roles and sessions",
        accent: "magenta",
        icon: "MessagesSquare",
        when: "Sep 13 to 18",
        items: [
          "Mention a role or a session in chat, and it wakes and answers in the thread.",
          "A Slack workspace mirrors into team chat, with each sender shown under their own name.",
          "Chat gained message search and an emoji picker, and the site has a public support chat.",
          "An agent can sit in a huddle as a participant, and a session can follow its own room's huddle live. Walkie became a click toggle: a face offers Talk, Ring and Message.",
        ],
        docs: [
          { href: "/documentation/team-chat", label: "Team chat" },
          { href: "/documentation/calls", label: "Huddles and walkie" },
        ],
      },
      {
        title: "Session characters and follow mode",
        accent: "violet",
        icon: "Users",
        when: "Sep 13 to 17",
        items: [
          "Every session wears a character: one of 24 painted animal faces and a short name. The same face marks the thread in the inbox, the tab strip, chat and the org chart.",
          "Follow mode keeps your view on what a teammate is looking at, and viewer presence shows who reads a conversation with you.",
          "Files an agent sends to you render in the conversation, on web and on mobile.",
        ],
      },
      {
        title: "Notifications and mobile",
        accent: "yellow",
        icon: "Bell",
        when: "Sep 1 to 19",
        items: [
          "Sessions that need input fold into one digest across the server, web, phone and desktop, in place of one alert for each session.",
          "The app reads notification permission from the OS and nudges once when the OS is silencing banners. A sounds panel has a switch for each category and a volume slider.",
          "An iOS Live Activity on the lock screen shows the work state of every live session.",
          "Mobile gets dark mode, chat as a top level tab, and deep links that map every web URL onto a screen.",
        ],
      },
      {
        title: "A calmer interface",
        accent: "cyan",
        icon: "AppWindow",
        when: "Sep 1 to 19",
        items: [
          "A minimal interface style strips the chrome down for reading.",
          "Side by side is a tab split: drag a session row onto the stage, or option click to open an object beside what you read.",
          "`ctrl+tab` walks the objects you visited most recently, and an entity reference renders as a card that reveals its object inline.",
          "On desktop, chat and work open as windows of their own.",
        ],
      },
    ],
  },
  {
    id: "2026-08",
    month: "August 2026",
    sortDate: "2026-08-01",
    version: "v1.1.95 – v1.1.113",
    desktop: "Desktop v1.1.98",
    headline: "Decisions, a browser for agents, and a team that talks",
    summary:
      "This month agents learned to ask. `cast decide` puts a question in a queue you clear in your own time, and a pinned state line says where each thread stands before you open it. Agents got a browser, a terminal you can watch from another machine, and images that render in the thread. Teams got chat, huddles with transcripts, and push to talk.",
    sections: [
      {
        title: "cast decide: a queue for decisions",
        accent: "yellow",
        icon: "Scale",
        when: "Aug 14 to 27",
        items: [
          "`cast decide` posts one question with its options, what each option costs, and the reasoning. It lands in a queue you clear in one sitting.",
          "The answer returns to the session as a message. A blocking ask ends the agent's turn; `--advisory --default` lets it continue on a default that is cheap to undo.",
          "Permission prompts from every session appear as cards in the same queue.",
          "A posted decision stays correct: `cast decide edit` rewrites it in place, `cancel` withdraws it, and `ls` shows each open ask.",
        ],
        docs: [{ href: "/documentation/decisions", label: "Decisions" }],
      },
      {
        title: "Pinned state, and an inbox that says who acts next",
        accent: "cyan",
        icon: "Pin",
        when: "Aug 4 to 17",
        items: [
          "`cast state` pins a short line above the composer and on the inbox card: what the session is doing, what it waits on, and what is yours to decide.",
          "Every surface shows how far the thread has run since the line was written, so a neglected state reads as neglected.",
          "A finished turn now settles as Done or Dormant as well as Needs Input. Done means delivered. Dormant means a trigger or a background task will wake it.",
          "A turn parked on background work shows as waiting, and the inbox has a view grouped by trigger.",
        ],
        docs: [{ href: "/documentation/thread-state", label: "Pinned thread state" }],
      },
      {
        title: "cast browser: a browser for agents",
        accent: "orange",
        icon: "Globe",
        when: "Aug 12 to 26",
        items: [
          "`cast browser` gives each session its own tab in one managed browser. The loop is a snapshot, then an action on an element ref.",
          "`do` runs several steps in one process, and screenshots land in the thread.",
          "Watch an agent's browser live and take control from the live view. A cloud host also has a view of its whole screen.",
        ],
        docs: [{ href: "/documentation/browser", label: "cast browser" }],
      },
      {
        title: "Terminals on any machine",
        accent: "green",
        icon: "Terminal",
        when: "Aug 2 to 13",
        items: [
          "Each conversation has its own terminal, in a panel that takes the full height.",
          "Watch a tmux pane that runs on another machine, and type into it. Frames and keystrokes ride one leased stream in both directions.",
          "`cast resume --tmux` attaches to the pane a session runs in.",
          "Each device reports the git health of its repos, and a git key for each device lets you grant one machine access to a repo.",
        ],
        docs: [{ href: "/documentation/remote-and-cloud-sessions", label: "Remote and cloud sessions" }],
      },
      {
        title: "Team chat",
        accent: "magenta",
        icon: "MessagesSquare",
        when: "Aug 12 to 30",
        items: [
          "Channels, direct messages and threads, with typing indicators and search. A threads inbox lists every conversation you are in.",
          "Task, plan and session ids render as live references, and any link sends to chat from every share surface.",
          "A reply on a session's thread is relayed into that session, so the agent reads it as a message.",
          "Chat and calls are features that each team turns on.",
        ],
        docs: [{ href: "/documentation/team-chat", label: "Team chat" }],
      },
      {
        title: "Huddles and walkie",
        accent: "violet",
        icon: "Phone",
        when: "Aug 14 to 28",
        items: [
          "A huddle is a call room with presence. Every huddle is transcribed with exact speaker attribution.",
          "A finished huddle leaves a digest where it was held: a title, a summary and action items. `cast calls` lets an agent read what was said.",
          "Walkie is push to talk, and a teammate's face is the key. A voice burst becomes a call only when somebody steps in, and rooms warm up ahead of a burst so the first word is not lost.",
          "Phones ring through VoIP pushes, and the people wall opens from anywhere with `cmd+shift+p`.",
        ],
        docs: [{ href: "/documentation/calls", label: "Huddles and walkie" }],
      },
      {
        title: "Images in the thread",
        accent: "blue",
        icon: "Image",
        when: "Aug 8 to 13",
        items: [
          "`cast image` uploads a screenshot and prints a link that renders inline in any reply.",
          "A session has an image gallery, inbox rows show a thumbnail, and images carry captions.",
          "Images that a shell command wrote render in the thread, and dead local image links in agent prose are rescued.",
          "Guests on a share link see images too.",
        ],
      },
      {
        title: "Tasks: subtasks, statuses and projects",
        accent: "green",
        icon: "ListChecks",
        when: "Aug 5 to 25",
        items: [
          "Subtasks nest under the task they serve. Closing a parent with open subtasks is refused until you finish them or pass `--cascade`.",
          "Each team defines its own task statuses, and kanban columns drag into order.",
          "`cast project` creates and lists projects, and the task list groups and filters by label.",
          "A project page charts its progress, and `cast task show` takes several ids and `--json`.",
        ],
        docs: [{ href: "/documentation/tasks-and-plans", label: "Tasks and plans" }],
      },
      {
        title: "The workbench",
        accent: "blue",
        icon: "LayoutDashboard",
        when: "Aug 2 to 27",
        items: [
          "Open a session beside a task, a doc or a plan. Layout modes became two gestures: peek and pin.",
          "Saved views, sidebar pins, and a context menu on every object. Saved layouts sit on `⌥1` to `⌥9`.",
          "The command palette covers every feature, `?` lists every shortcut, and `r` quotes your selection into the reply.",
          "On desktop, a tab detaches into its own window, and `Cmd+N` pops a window out at once.",
        ],
      },
      {
        title: "Files: your markdown, in the app",
        accent: "yellow",
        icon: "FolderOpen",
        when: "Aug 1 to 21",
        items: [
          "Vault is now Files. Register a directory of markdown and the daemon serves it to the Files page. The files stay on your machine unless you turn on a mirror for your other devices.",
          "Live preview editing, daily notes, bookmarks, heading folds, a find bar and a quick switcher.",
          "`cast vault` searches, reads and writes notes from the terminal, and a change shows in an open tab within a second.",
        ],
      },
      {
        title: "Pages and canvas",
        accent: "cyan",
        icon: "FileText",
        when: "Aug 2 to 27",
        items: [
          "Artifacts are now pages, managed from the CLI with `cast publish ls` and `rm`. Viewers see the list of comments on a page.",
          "A published page embeds in the conversation that links it.",
          "The canvas gained declarative widgets: tabs, sortable tables, tooltips and charts, with a collapse for tall canvases and a wide layout.",
          "Share pages render on the server, and the docs gained deep dive guides.",
        ],
        docs: [
          { href: "/documentation/publish", label: "Published pages" },
          { href: "/documentation/visual-canvas", label: "The visual canvas" },
        ],
      },
      {
        title: "More agents, more machines",
        accent: "violet",
        icon: "Boxes",
        when: "Aug 3 to 26",
        items: [
          "Grok Build joins Claude Code, Codex, Cursor, Gemini, OpenCode and pi as a client.",
          "Windows installs and starts on boot through WSL, and one command takes a new machine from nothing to synced.",
          "The stable context feed installs for Codex, Cursor and OpenCode, and the model picker sets a default model for each agent client.",
          "`cast usage` shows your account's usage windows and reset times, and a session parked on a limit continues when the window resets.",
          "A capabilities page compares skills, MCP servers and plugins across your machines and shows where they drift.",
        ],
        docs: [{ href: "/documentation/usage-limits", label: "Usage limits" }],
      },
      {
        title: "Sync you can see, and a lighter client",
        accent: "green",
        icon: "Activity",
        when: "Aug 2 to 28",
        items: [
          "The sync chip says what the sync is doing, by scope.",
          "The backend keeps an append only sync log for each scope, with positions and acks. The client applies new entries in place of receiving whole query results again.",
          "Heartbeat fields moved off the session rows, so a heartbeat every second no longer pushes or renders the whole inbox again.",
          "We removed the session replay recorders, and tasks, triggers, workflows and devices now paint from the local store.",
        ],
        docs: [{ href: "/documentation/sync-engine", label: "How the client syncs" }],
      },
      {
        title: "Notifications and security",
        accent: "red",
        icon: "ShieldCheck",
        when: "Aug 2 to 17",
        items: [
          "Push routing knows where you are: the phone stays quiet while you are at a machine, and a storm of alerts arrives as one.",
          "API tokens bind to their device, and signup verifies your email.",
          "We closed reads across tenants on public functions and removed a public endpoint that confirmed whether a token was valid.",
          "Kill is final: it forces the teardown, cancels queued messages, and every surface shows the session as killed.",
        ],
      },
    ],
  },
];
