type Skill = { name: string; description: string };

const CLAUDE_CODE: Skill[] = [
  { name: "help", description: "Show help and available commands" },
  { name: "login", description: "Sign in to your Anthropic account" },
  { name: "logout", description: "Sign out from your Anthropic account" },
  { name: "clear", description: "Clear conversation history and free up context" },
  { name: "compact", description: "Compact conversation with optional focus instructions" },
  { name: "model", description: "Select or change the AI model" },
  { name: "fast", description: "Toggle fast mode" },
  { name: "diff", description: "Show uncommitted changes" },
  { name: "config", description: "Open settings interface" },
  { name: "cost", description: "Show token usage statistics" },
  { name: "usage", description: "Show plan usage limits and rate limit status" },
  { name: "context", description: "Visualize current context usage" },
  { name: "copy", description: "Copy last response to clipboard" },
  { name: "resume", description: "Resume a conversation by ID or name" },
  { name: "exit", description: "Exit the CLI" },
  { name: "plan", description: "Enter plan mode" },
  { name: "permissions", description: "View or update permissions" },
  { name: "mcp", description: "Manage MCP server connections" },
  { name: "memory", description: "Edit CLAUDE.md memory files" },
  { name: "init", description: "Initialize project with a CLAUDE.md guide" },
  { name: "feedback", description: "Submit feedback about Claude Code" },
  { name: "theme", description: "Change the color theme" },
  { name: "vim", description: "Toggle between Vim and Normal editing modes" },
  { name: "status", description: "Show version, model, account, and connectivity" },
  { name: "rename", description: "Rename the current session" },
  { name: "export", description: "Export the current conversation" },
  { name: "branch", description: "Branch the conversation at this point" },
  { name: "rewind", description: "Rewind conversation and/or code to a previous point" },
  { name: "skills", description: "List available skills" },
  { name: "agents", description: "Manage agent configurations" },
  { name: "hooks", description: "View hook configurations" },
  { name: "btw", description: "Ask a quick side question" },
  { name: "doctor", description: "Diagnose and verify installation" },
  { name: "effort", description: "Set the model effort level" },
  { name: "pr-comments", description: "Fetch PR comments from GitHub" },
  { name: "voice", description: "Toggle push-to-talk voice dictation" },
  { name: "chrome", description: "Configure Chrome integration" },
  { name: "desktop", description: "Continue session in desktop app" },
  { name: "sandbox", description: "Toggle sandbox mode" },
  { name: "tasks", description: "List and manage background tasks" },
  { name: "stats", description: "Visualize daily usage and session history" },
  { name: "plugin", description: "Manage Claude Code plugins" },
  { name: "security-review", description: "Analyze changes for security vulnerabilities" },
  { name: "release-notes", description: "View the full changelog" },
  { name: "ide", description: "Manage IDE integrations" },
  { name: "color", description: "Set the prompt bar color" },
  { name: "add-dir", description: "Add a working directory to the session" },
  { name: "statusline", description: "Configure the status line" },
  { name: "remote-control", description: "Enable remote control from claude.ai" },
];

const CODEX: Skill[] = [
  { name: "clear", description: "Clear the terminal and start a fresh chat" },
  { name: "compact", description: "Summarize the conversation to free tokens" },
  { name: "copy", description: "Copy the latest Codex output" },
  { name: "diff", description: "Show the Git diff including untracked files" },
  { name: "exit", description: "Exit the CLI" },
  { name: "fast", description: "Toggle fast mode" },
  { name: "feedback", description: "Send logs to Codex maintainers" },
  { name: "fork", description: "Fork the current conversation" },
  { name: "init", description: "Generate an AGENTS.md scaffold" },
  { name: "logout", description: "Sign out of Codex" },
  { name: "mcp", description: "List configured MCP tools" },
  { name: "mention", description: "Attach a file to the conversation" },
  { name: "model", description: "Choose the active model" },
  { name: "new", description: "Start a new conversation" },
  { name: "permissions", description: "Set what Codex can do without asking" },
  { name: "personality", description: "Choose a communication style" },
  { name: "plan", description: "Switch to plan mode" },
  { name: "quit", description: "Exit the CLI" },
  { name: "resume", description: "Resume a saved conversation" },
  { name: "review", description: "Ask Codex to review your working tree" },
  { name: "status", description: "Display session config and token usage" },
  { name: "agent", description: "Switch the active agent thread" },
  { name: "apps", description: "Browse apps and connectors" },
  { name: "ps", description: "Show background terminals and output" },
  { name: "debug-config", description: "Print config diagnostics" },
  { name: "statusline", description: "Configure status-line fields" },
  { name: "experimental", description: "Toggle experimental features" },
];

const GEMINI: Skill[] = [
  { name: "help", description: "Show usage information about commands" },
  { name: "clear", description: "Clear the terminal screen" },
  { name: "compress", description: "Condense chat context to reduce token usage" },
  { name: "copy", description: "Copy last Gemini output to clipboard" },
  { name: "exit", description: "Exit the application" },
  { name: "init", description: "Generate a GEMINI.md context file" },
  { name: "mcp", description: "List MCP servers and their tools" },
  { name: "memory", description: "Manage GEMINI.md instructional context" },
  { name: "settings", description: "View and modify CLI configuration" },
  { name: "stats", description: "Show token usage and session duration" },
  { name: "theme", description: "Change the visual appearance" },
  { name: "vim", description: "Toggle vim-mode editing" },
  { name: "auth", description: "Switch authentication methods" },
  { name: "about", description: "Display version information" },
  { name: "bug", description: "File issues about Gemini CLI" },
  { name: "chat", description: "Manage conversation history" },
  { name: "checkpoint", description: "Save and resume conversation state" },
  { name: "directory", description: "Handle workspace directories" },
  { name: "editor", description: "Open text editor selection" },
  { name: "extensions", description: "Display active extensions" },
  { name: "restore", description: "Revert files to pre-execution state" },
  { name: "tools", description: "List available tools" },
  { name: "privacy", description: "View privacy notice and data preferences" },
  { name: "quit", description: "Exit the application" },
];

const BUILTIN_COMMANDS: Record<string, Skill[]> = {
  claude_code: CLAUDE_CODE,
  codex: CODEX,
  gemini: GEMINI,
};

export function getBuiltinCommands(agentType?: string): Skill[] {
  return BUILTIN_COMMANDS[agentType || "claude_code"] || CLAUDE_CODE;
}
