// The shipped `line` graph as the web reads it (docs/architecture/the-line.md
// L2, plan pl-838 step 3). The web has no DOT parser and no copy of the
// template files, so this module renders the parsed template, through the
// same serializer `cast workflow run` and `cast workflow push` send, into a
// committed snapshot under packages/web/lib/line. `shippedLine.test.ts`
// fails when the template moves and the snapshot did not; regenerate with
//
//   bun packages/cli/scripts/gen-shipped-line.ts
import lineCast from "./templates/line.cast" with { type: "text" };
import { BUILTIN_WORKFLOW_TEMPLATES } from "./templates";
import { parseWorkflowSource } from "./parser";
import { graphToPushPayload } from "./runner";

export const SHIPPED_LINE_SNAPSHOT_PATH = "packages/web/lib/line/shippedLine.generated.ts";

/** The snapshot's data: the push payload of the builtin, the raw source (its
 *  graph attributes, the stack among them, which a pushed row reads back from
 *  `source`), and the file each station's prompt or script ships in. */
export function shippedLineSnapshot() {
  const graph = parseWorkflowSource(BUILTIN_WORKFLOW_TEMPLATES.line);
  const { nodes, edges, stack } = graphToPushPayload(graph);
  // Parsed without a dir, every `@line/<file>` reference stays a reference.
  const raw = parseWorkflowSource(lineCast);
  const files: Record<string, { prompt?: string; script?: string }> = {};
  for (const n of raw.nodes.values()) {
    const ref = (v?: string) => (v?.startsWith("@") ? v.slice(1) : undefined);
    const prompt = ref(n.prompt);
    const script = ref(n.script);
    if (prompt || script) files[n.id] = { ...(prompt ? { prompt } : {}), ...(script ? { script } : {}) };
  }
  return { name: graph.name, goal: graph.goal, stack, source: lineCast, nodes, edges, files };
}

/** The snapshot file's whole text. */
export function renderShippedLineModule(): string {
  return [
    "// GENERATED by `bun packages/cli/scripts/gen-shipped-line.ts` from",
    "// packages/cli/src/workflow/templates/line.cast and templates/line/*. Do not",
    "// edit: packages/cli/src/workflow/shippedLine.test.ts fails on drift.",
    'import type { ShippedLine } from "./lineStations";',
    "",
    `export const SHIPPED_LINE: ShippedLine = ${JSON.stringify(shippedLineSnapshot(), null, 2)};`,
    "",
  ].join("\n");
}
