import assert from "node:assert/strict";
import { mock, test } from "bun:test";
import { replaceGlobals } from "../../test-helpers/globals";
import { closeDomWindow } from "../../test-helpers/domGlobals";

async function verifySlackComposer() {
  const { JSDOM } = await import("jsdom");
  const dom = new JSDOM('<div id="root"></div>', { url: "https://local.codecast.sh/chat/dm?m=root" });
  const restore = replaceGlobals({ window: dom.window, document: dom.window.document, navigator: dom.window.navigator, IS_REACT_ACT_ENVIRONMENT: true });
  const React = await import("react");
  const { act } = React;
  const { createRoot } = await import("react-dom/client");
  const { LINK_DEFAULTS } = await import("@codecast/convex/convex/lib/slackMirror");
  let link: any = { _id: "link", team_id: "team", chat_channel_id: "dm", kind: "dm", direction: "both", options: LINK_DEFAULTS, viewer_user_id: "samvit", viewer_slack_auth: "connect" };
  const sent: any[] = [];
  const opened: string[] = [];
  const requested: any[] = [];
  const captured: unknown[] = [];
  let answer: () => Promise<any> = async () => ({ ok: true, url: "https://slack.com/oauth/v2/authorize?test=1" });
  mock.module("convex/react", () => ({ useAction: () => async (args: unknown) => { requested.push(args); return answer(); } }));
  mock.module("@sentry/react", () => ({ captureException: (error: unknown) => captured.push(error) }));
  mock.module("../../lib/desktop", () => ({ openExternalUrl: (url: string) => opened.push(url) }));
  mock.module("../../store/inboxStore", () => ({ useTrackedStore: () => ({ currentUser: { _id: "samvit" } }) }));
  mock.module("./SlackSyncDialog", () => ({ useChannelSlackLink: () => link }));
  mock.module("../../hooks/useChatTyping", () => ({ useTypingReporter: () => ({ stop() {}, onTyping() {} }), useTypingMembers: () => [] }));
  mock.module("./TypingIndicator", () => ({ TypingIndicator: () => null }));
  mock.module("../calls/WalkiePtt", () => ({ WalkiePttButton: () => null }));
  mock.module("../KeyboardShortcutsHelp", () => ({ KeyCap: ({ children }: any) => <kbd>{children}</kbd>, MenuKeyCaps: () => null }));
  mock.module("../ui/popover", () => ({ Popover: ({ children }: any) => <div>{children}</div>, PopoverTrigger: ({ children }: any) => children, PopoverContent: ({ children }: any) => <div>{children}</div> }));
  mock.module("../../lib/draftImages", () => ({ settleComposerAttachments: async () => [] }));
  mock.module("../MessageInput", () => ({ MessageInput: ({ onGateSend }: any) => {
    const [text, setText] = React.useState("Draft survives authorization");
    return <><textarea value={text} onChange={event => setText(event.target.value)} /><button type="button" data-send onClick={() => onGateSend(text, [])}>Send</button></>;
  } }));
  const { ChatComposer } = await import("./ChatComposer");
  const root = createRoot(document.getElementById("root")!);
  const render = (threadRootId?: string) => act(async () => root.render(<ChatComposer channelId="dm" teamId="team" threadRootId={threadRootId} placeholder="Message Samvit" onSend={(...args) => sent.push(args)} />));
  const checkbox = () => document.querySelector<HTMLInputElement>('.ch-composer-choice input')!;
  const button = () => document.querySelector<HTMLButtonElement>('.ch-slack-connect-button')!;
  try {
    await render("root");
    assert.match(document.body.textContent!, /Your messages stay in Codecast/);
    assert.equal(checkbox().checked, false);
    assert.equal(checkbox().disabled, true);
    await act(async () => document.querySelector<HTMLButtonElement>('[data-send]')!.click());
    assert.deepEqual(sent[0][2], { syncLocalOnly: true });
    const draft = document.querySelector("textarea")!;
    await act(async () => button().click());
    assert.deepEqual(requested[0], { scope_type: "self", team_id: "team", return_to: "/chat/dm?m=root", origin: "https://local.codecast.sh" });
    assert.equal(opened.length, 1);
    assert.match(document.body.textContent!, /Finish connecting in Slack/);
    assert.equal(document.querySelector("textarea"), draft);
    assert.equal(draft.value, "Draft survives authorization");
    link = { ...link, viewer_slack_auth: "ready" };
    await render("root");
    assert.equal(document.querySelector(".ch-slack-connect"), null);
    assert.equal(checkbox().disabled, false);
    assert.equal(checkbox().checked, true);
    assert.match(checkbox().parentElement!.textContent!, /Also send to Slack$/);
    assert.equal(document.querySelector("textarea"), draft);
    await act(async () => document.querySelector<HTMLButtonElement>('[data-send]')!.click());
    assert.equal(sent[1][2], undefined);
    await act(async () => checkbox().click());
    await act(async () => document.querySelector<HTMLButtonElement>('[data-send]')!.click());
    assert.deepEqual(sent[2][2], { syncLocalOnly: true });
    assert.equal(checkbox().checked, true);
    link = { ...link, viewer_slack_auth: "reconnect" };
    await render();
    assert.match(document.body.textContent!, /Slack needs permission to send as you/);
    assert.equal(button().textContent, "Allow replies");
    answer = async () => { throw new Error("offline"); };
    await act(async () => button().click());
    assert.match(document.querySelector('[role="alert"]')!.textContent!, /Couldn’t open Slack/);
    assert.equal(captured.length, 1);
    assert.equal(opened.length, 1);
    let resolve!: (result: any) => void;
    answer = () => new Promise(done => { resolve = done; });
    await act(async () => { button().click(); button().click(); });
    assert.equal(button().disabled, true);
    assert.equal(requested.length, 3);
    await act(async () => resolve({ ok: true, url: "https://slack.com/oauth/v2/authorize?test=2" }));
    assert.equal(button().disabled, false);
    assert.equal(document.querySelector('[role="alert"]'), null);
    link = { ...link, viewer_user_id: "ashot", viewer_slack_auth: "ready" };
    await render();
    assert.match(document.body.textContent!, /Checking your Slack connection/);
    assert.equal(checkbox().checked, false);
    assert.equal(checkbox().disabled, true);
    await act(async () => document.querySelector<HTMLButtonElement>('[data-send]')!.click());
    assert.deepEqual(sent.at(-1)[2], { syncLocalOnly: true });
    link = { ...link, kind: "channel", slack_channel_name: "testing" };
    await render();
    assert.equal(checkbox().checked, true);
    assert.match(checkbox().parentElement!.textContent!, /Also send to Slack #testing/);
    link = { ...link, paused: true };
    await render();
    assert.equal(document.querySelector(".ch-slack-connect"), null);
    assert.equal(checkbox(), null);
  } finally {
    await act(async () => root.unmount());
    closeDomWindow(dom);
    restore();
  }
  console.log("Slack composer authorization, draft preservation, delivery, and retry: passed");
}

test("Slack composer authorization preserves drafts and enables delivery", verifySlackComposer, 30_000);
