#!/usr/bin/env bash
# Mirror the shared @platform packages from the canonical repo into this
# tree. The copy under platform/packages is GENERATED: never edit it by hand.
# It is what ships, because Railway, the CLI release workflow and the desktop
# build all run from a fresh clone, so every dep points one level in
# (file:../../platform/packages/<name>) and never outside the checkout.
# Edit the canonical copy in ~/src/platform, then run this to refresh.
#
#   scripts/vendor-platform.sh                   # refresh the mirror
#   scripts/vendor-platform.sh --check           # exit 1 if the mirror has drifted
#   scripts/vendor-platform.sh --check-manifest  # exit 1 if the mirror is inconsistent (no canonical repo needed)
#   scripts/vendor-platform.sh --write-manifest  # regenerate the manifest from the mirror
#   scripts/vendor-platform.sh --list            # print the mirrored package names
#   scripts/vendor-platform.sh --list-with-tests # print the ones that have a test suite
#
# --check needs the canonical repo, so CI cannot run it: a GitHub runner has no
# ~/src/platform. --check-manifest is the runner's half. It re-hashes the mirror
# against platform/vendor-manifest.txt and re-reads the dep lines the mirror was
# generated from, so it catches a hand-edited mirror, a package adopted without a
# re-vendor, and a dep pointing outside the checkout. A mirror that is merely
# STALE against a newer canonical repo stays invisible to it, because nothing on
# a runner can see that repo (ct-49675).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${PLATFORM_SRC:-$HOME/src/platform/packages}"
MANIFEST="$ROOT/platform/vendor-manifest.txt"
MODE="${1:-vendor}"

# The set is whatever the workspace packages depend on, so adopting a new
# package is one dep line and a rerun, never a second list to maintain.
DEP_LINE='"@platform/[a-z-]*": "file:\.\./\.\./platform/packages/[a-z-]*"'
list_packages() {
  grep -ho "$DEP_LINE" "$ROOT"/packages/*/package.json \
    | sed 's#.*platform/packages/\([a-z-]*\)"#\1#' | sort -u
}

# `bun test` matches **{.test,.spec,_test_,_spec_}.{js,ts,jsx,tsx} and exits 1
# when nothing matches, so the CI loop has to ask before it runs. Asking with a
# narrower pattern is worse than not asking: *.test.ts alone skips
# @platform/desktop, whose suite is entirely .test.js, and skips it silently.
has_tests() {
  [[ -n "$(find "$1" \( -name node_modules -o -name dist \) -prune -o \
    \( -name '*.test.*' -o -name '*.spec.*' -o -name '*_test_*' -o -name '*_spec_*' \) \
    -print -quit 2>/dev/null)" ]]
}

list_testable() {
  local p
  for p in $(list_packages); do
    if has_tests "$ROOT/platform/packages/$p"; then
      echo "$p"
    else
      echo "platform/packages/$p has no tests" >&2
    fi
  done
}

RSYNC=(rsync -a --delete --exclude node_modules --exclude dist --exclude '*.tsbuildinfo' --exclude '*.probe.ts')
if command -v sha256sum >/dev/null 2>&1; then SHA=(sha256sum); else SHA=(shasum -a 256); fi

# One content hash per mirrored package: every file the vendor copy carries,
# path and bytes, in a stable order. The excludes match RSYNC's, plus the
# bun.lock a per-package `bun install` leaves behind (CI installs into the
# mirror to run its tests, and that must not read as drift).
tree_hash() {
  # -prune, not a path filter: a mirror that has been installed into carries a
  # node_modules far larger than the package, and walking it makes the check
  # slow enough to look hung.
  ( cd "$1" && find . \( -name node_modules -o -name dist \) -prune -o -type f \
      ! -name '*.tsbuildinfo' ! -name '*.probe.ts' \
      ! -name 'bun.lock' ! -name '.DS_Store' \
      -exec "${SHA[@]}" {} + | LC_ALL=C sort -k2 ) | "${SHA[@]}" | cut -d' ' -f1
}

write_manifest() {
  {
    echo "# Generated by scripts/vendor-platform.sh. Do not edit by hand."
    echo "# <sha256 of the mirrored files>  <package>"
    for p in $(list_packages); do
      printf '%s  %s\n' "$(tree_hash "$ROOT/platform/packages/$p")" "$p"
    done
  } > "$MANIFEST"
  echo "wrote ${MANIFEST#"$ROOT"/}"
}

# Everything a runner can prove about the mirror without the canonical repo.
check_manifest() {
  local drift=0 p expected actual

  # 1. Every @platform dep points inside the checkout, at its own name. A dep
  # resolving outside breaks the fresh-clone builds this mirror exists for, and
  # list_packages would not even see it.
  # Only string-valued entries: an @platform key under peerDependenciesMeta
  # holds an object and declares no path at all.
  local stray
  stray=$(grep -n '"@platform/[a-z-]*": *"' "$ROOT"/packages/*/package.json \
    | grep -v "$DEP_LINE" || true)
  if [[ -n "$stray" ]]; then
    echo "@platform deps that do not point at file:../../platform/packages/<name>:"
    echo "$stray" | sed "s#^$ROOT/#  #"
    drift=1
  fi
  local mismatched
  mismatched=$(grep -ho "$DEP_LINE" "$ROOT"/packages/*/package.json \
    | sed 's#"@platform/\([a-z-]*\)": "file:../../platform/packages/\([a-z-]*\)"#\1 \2#' \
    | awk '$1 != $2 { print "  " $1 " resolves to platform/packages/" $2 }' | sort -u)
  if [[ -n "$mismatched" ]]; then
    echo "@platform deps whose name and directory disagree:"; echo "$mismatched"; drift=1
  fi

  local packages; packages=$(list_packages)

  # 2. Every declared package is actually mirrored, under its own name.
  for p in $packages; do
    if [[ ! -f "$ROOT/platform/packages/$p/package.json" ]]; then
      echo "platform/packages/$p is declared as a dep but not mirrored: run scripts/vendor-platform.sh"
      drift=1
      continue
    fi
    local declared
    declared=$(grep -o '"name": *"[^"]*"' "$ROOT/platform/packages/$p/package.json" | head -1 | sed 's#.*"name": *"\(.*\)"#\1#')
    if [[ "$declared" != "@platform/$p" ]]; then
      echo "platform/packages/$p declares itself as $declared"
      drift=1
    fi
  done

  # 3. No mirrored package that nothing depends on. A leftover directory ships
  # to every fresh clone and no vendor run ever refreshes it.
  if [[ -d "$ROOT/platform/packages" ]]; then
    for dir in "$ROOT"/platform/packages/*/; do
      [[ -d "$dir" ]] || continue
      p=$(basename "$dir")
      if ! grep -qx "$p" <<<"$packages"; then
        echo "platform/packages/$p is mirrored but no workspace package depends on it"
        drift=1
      fi
    done
  fi

  # 4. The mirror's bytes are the ones the last vendor run produced.
  if [[ ! -f "$MANIFEST" ]]; then
    echo "${MANIFEST#"$ROOT"/} is missing: run scripts/vendor-platform.sh --write-manifest"
    return 1
  fi
  local listed; listed=$(awk '!/^#/ && NF { print $2 }' "$MANIFEST" | sort -u)
  if [[ "$listed" != "$packages" ]]; then
    echo "${MANIFEST#"$ROOT"/} covers a different package set than the workspace deps:"
    diff <(echo "$listed") <(echo "$packages") | sed 's/^/  /' || true
    drift=1
  fi
  for p in $packages; do
    [[ -d "$ROOT/platform/packages/$p" ]] || continue
    expected=$(awk -v p="$p" '!/^#/ && $2 == p { print $1 }' "$MANIFEST")
    actual=$(tree_hash "$ROOT/platform/packages/$p")
    if [[ -n "$expected" && "$expected" != "$actual" ]]; then
      echo "platform/packages/$p does not match the manifest: it was edited by hand, or vendored without updating ${MANIFEST#"$ROOT"/}"
      drift=1
    fi
  done

  if [[ $drift -eq 0 ]]; then echo "vendored platform packages are internally consistent"; fi
  return $drift
}

case "$MODE" in
  --list) list_packages; exit 0 ;;
  --list-with-tests) list_testable; exit 0 ;;
  --write-manifest) write_manifest; exit 0 ;;
  --check-manifest) if check_manifest; then exit 0; else exit 1; fi ;;
  --check|vendor) ;;
  *) echo "unknown mode: $MODE" >&2; exit 2 ;;
esac

PACKAGES=$(list_packages)

if [[ "$MODE" == "--check" ]]; then
  drift=0
  for p in $PACKAGES; do
    out=$("${RSYNC[@]}" -n -i "$SRC/$p/" "$ROOT/platform/packages/$p/" | grep -v '^\.d' || true)
    if [[ -n "$out" ]]; then echo "platform/packages/$p differs from $SRC/$p:"; echo "$out" | sed 's/^/  /'; drift=1; fi
  done
  [[ $drift -eq 0 ]] && echo "vendored platform packages match $SRC"
  exit $drift
fi

for p in $PACKAGES; do
  mkdir -p "$ROOT/platform/packages/$p"
  "${RSYNC[@]}" "$SRC/$p/" "$ROOT/platform/packages/$p/"
done
echo "vendored $(echo "$PACKAGES" | wc -w | tr -d ' ') packages from $SRC: $(echo $PACKAGES)"
# The manifest is what CI re-checks without the canonical repo, so it is only
# ever true right after a real vendor run.
write_manifest

# bun materializes file: deps as COPIES under node_modules/.bun, and keeps
# serving the copy after the mirror changes; vite then pre-bundles the old copy
# into packages/web/node_modules/.vite and serves that. Purge the copies and
# reinstall, then purge the vite cache. The cache goes last: a running dev
# server (plugins/depsCacheGuard.ts) restarts itself when the cache disappears,
# and it must rebuild against a finished node_modules, not one bun is still
# writing.
rm -rf "$ROOT"/node_modules/.bun/@platform+*
(cd "$ROOT" && bun install --silent)
rm -rf "$ROOT"/packages/web/node_modules/.vite
echo "re-materialized the @platform copies and cleared the vite cache"
