import { describe, expect, test } from "bun:test";
import { makeFakeDb } from "./testDb";
import { webCreate, webUpdate, webList, webDelete, webReorder } from "./steeringItems";
import { webCreateLink } from "./objectLinks";
import { isAllowedLink } from "./lib/steering";

const OWNER="u_owner", MEMBER="u_member", STRANGER="u_stranger", TEAM="t_team", OTHER="t_other";
function auth(id:string|null){return{getUserIdentity:async()=>id?{subject:`${id}|session`}:null};}
function tables(extra:Record<string,any[]>={}):Record<string,any[]>{return{users:[{_id:OWNER},{_id:MEMBER},{_id:STRANGER}],teams:[{_id:TEAM},{_id:OTHER}],team_memberships:[{_id:"m1",user_id:OWNER,team_id:TEAM,role:"admin"},{_id:"m2",user_id:MEMBER,team_id:TEAM,role:"member"},{_id:"m3",user_id:STRANGER,team_id:OTHER,role:"admin"}],client_state:[],counters:[],change_log:[],steering_items:[],entity_links:[],entity_conversations:[],...extra};}
function ctx(id:string|null,t:Record<string,any[]>){return{auth:auth(id),db:makeFakeDb(t),scheduler:{runAfter:async()=>null}} as any;}
function item(over:Record<string,any>={}){return{_id:"si_1",short_id:"si-1",kind:"objective",title:"Repeatable demand",priority:"high",status:"active",user_id:OWNER,team_id:TEAM,owner_id:OWNER,created_at:1,updated_at:1,...over};}

describe("recursive typed steering items",()=>{
  test("all four kinds use one ordered collection",async()=>{const t=tables();for(const kind of ["objective","bet","initiative","question"])await(webCreate as any)._handler(ctx(OWNER,t),{kind,title:kind});expect(t.steering_items.map(i=>i.kind)).toEqual(["objective","bet","initiative","question"]);expect(t.steering_items.map(i=>i.sort_order)).toEqual([1,2,3,4]);expect(t.steering_items.every(i=>i.short_id.startsWith("si-"))).toBe(true);});
  test("kind-aware validation rejects foreign fields",async()=>{const t=tables();await expect((webCreate as any)._handler(ctx(OWNER,t),{kind:"objective",title:"Wrong",hypothesis:"bet-only"})).rejects.toThrow();expect(t.steering_items).toHaveLength(0);});
  test("lifecycle validation is kind-aware",async()=>{const t=tables();await expect((webCreate as any)._handler(ctx(OWNER,t),{kind:"question",title:"Wrong state",status:"achieved"})).rejects.toThrow();const created=await(webCreate as any)._handler(ctx(OWNER,t),{kind:"question",title:"Open question"});expect(t.steering_items.find(i=>i._id===created.id)?.status).toBe("open");});
  test("kind changes remap lifecycle and ordinary edits can repair old rows",async()=>{const t=tables({steering_items:[item({status:"legacy-state"})]});await(webUpdate as any)._handler(ctx(OWNER,t),{id:"si_1",priority:"low"});await(webUpdate as any)._handler(ctx(OWNER,t),{id:"si_1",kind:"question"});expect(t.steering_items[0].status).toBe("open");});
  test("child creation inherits its parent's workspace",async()=>{const t=tables({steering_items:[item()]});const created=await(webCreate as any)._handler(ctx(OWNER,t),{kind:"initiative",title:"Child",parent_item_id:"si_1",workspace:"personal"});expect(t.steering_items.find(i=>i._id===created.id)?.team_id).toBe(TEAM);});
  test("mixed nesting works and cycles fail",async()=>{const t=tables({steering_items:[item(),item({_id:"si_2",short_id:"si-2",kind:"question",title:"Who buys?",status:"open",parent_item_id:"si_1"})]});await(webUpdate as any)._handler(ctx(MEMBER,t),{id:"si_2",priority:"urgent"});expect(t.steering_items[1].priority).toBe("urgent");await expect((webUpdate as any)._handler(ctx(MEMBER,t),{id:"si_1",parent_item_id:"si_2"})).rejects.toThrow();});
  test("workspace reads fail closed",async()=>{const t=tables({steering_items:[item()]});expect(await(webList as any)._handler(ctx(MEMBER,t),{workspace:"team",team_id:TEAM})).toHaveLength(1);expect(await(webList as any)._handler(ctx(STRANGER,t),{workspace:"team",team_id:TEAM})).toEqual([]);});
  test("typed links enforce item-kind semantics",async()=>{const t=tables({steering_items:[item(),item({_id:"si_i",short_id:"si-2",kind:"initiative",title:"Pilot"}),item({_id:"si_b",short_id:"si-3",kind:"bet",title:"Buyers pay"})]});expect(isAllowedLink("steering_item","advances","steering_item")).toBe(true);await(webCreateLink as any)._handler(ctx(MEMBER,t),{from_type:"steering_item",from_id:"si_i",link_type:"advances",to_type:"steering_item",to_id:"si_1"});await expect((webCreateLink as any)._handler(ctx(MEMBER,t),{from_type:"steering_item",from_id:"si_1",link_type:"tests",to_type:"steering_item",to_id:"si_b"})).rejects.toThrow();});
  test("deletion refuses children",async()=>{const t=tables({steering_items:[item(),item({_id:"si_2",short_id:"si-2",parent_item_id:"si_1"})]});await expect((webDelete as any)._handler(ctx(OWNER,t),{id:"si_1"})).rejects.toThrow();});
  test("reorder swaps siblings in one mutation",async()=>{const t=tables({steering_items:[item({sort_order:1}),item({_id:"si_2",short_id:"si-2",sort_order:2})]});await(webReorder as any)._handler(ctx(OWNER,t),{id:"si_1",before_id:"si_2"});expect(t.steering_items.map(i=>i.sort_order)).toEqual([2,1]);});
});
